# **INGEST**

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('/content/DS-01/data/raw_data/Ass1.csv')
df

   Height  Weight  Age  Grip Strength Frailty
0    65.8     112   30             30       N
1    71.5     136   19             31       N
2    69.4     153   45             29       N
3    68.2     142   22             28       Y
4    67.8     144   29             24       Y
5    68.7     123   50             26       N
6    69.8     141   51             22       Y
7    70.1     136   23             20       Y
8    67.9     112   17             19       N
9    66.8     120   39             31       N

# **PROCESS**

a. Unit Standardization

In [20]:
df["Height"] = df["Height"] * 0.0254
df["Weight"] = df["Weight"] * 0.45359237
df

    Height     Weight  Age  Grip Strength Frailty
0  1.67132  50.802345   30             30       N
1  1.81610  61.688562   19             31       N
2  1.76276  69.399633   45             29       N
3  1.73228  64.410117   22             28       Y
4  1.72212  65.317301   29             24       Y
5  1.74498  55.791862   50             26       N
6  1.77292  63.956524   51             22       Y
7  1.78054  61.688562   23             20       Y
8  1.72466  50.802345   17             19       N
9  1.69672  54.431084   39             31       N

b. Feature Engineering

In [21]:
df["BMI"] = (df["Weight"] / (df["Height"] ** 2)).round(2)
df

    Height     Weight  Age  Grip Strength Frailty    BMI
0  1.67132  50.802345   30             30       N  18.19
1  1.81610  61.688562   19             31       N  18.70
2  1.76276  69.399633   45             29       N  22.33
3  1.73228  64.410117   22             28       Y  21.46
4  1.72212  65.317301   29             24       Y  22.02
5  1.74498  55.791862   50             26       N  18.32
6  1.77292  63.956524   51             22       Y  20.35
7  1.78054  61.688562   23             20       Y  19.46
8  1.72466  50.802345   17             19       N  17.08
9  1.69672  54.431084   39             31       N  18.91

In [22]:
def age_grp(age):
  if age < 30:
    return "<30"
  elif 30 <= age <= 45:
    return "30-45"
  elif 46 <= age <= 60:
    return "46-60"
  else:
    return ">60"

df["age_grp"] = df["Age"].apply(age_grp)
df

    Height     Weight  Age  Grip Strength Frailty    BMI age_grp
0  1.67132  50.802345   30             30       N  18.19   30-45
1  1.81610  61.688562   19             31       N  18.70     <30
2  1.76276  69.399633   45             29       N  22.33   30-45
3  1.73228  64.410117   22             28       Y  21.46     <30
4  1.72212  65.317301   29             24       Y  22.02     <30
5  1.74498  55.791862   50             26       N  18.32   46-60
6  1.77292  63.956524   51             22       Y  20.35   46-60
7  1.78054  61.688562   23             20       Y  19.46     <30
8  1.72466  50.802345   17             19       N  17.08     <30
9  1.69672  54.431084   39             31       N  18.91   30-45

C. Categorical → numeric encoding

In [23]:
import numpy as np
df["Frailty_norm"] = df["Frailty"].map({"Y": 1, "N": 0}).astype(np.int8)
df

    Height     Weight  Age  Grip Strength Frailty    BMI age_grp  Frailty_norm
0  1.67132  50.802345   30             30       N  18.19   30-45             0
1  1.81610  61.688562   19             31       N  18.70     <30             0
2  1.76276  69.399633   45             29       N  22.33   30-45             0
3  1.73228  64.410117   22             28       Y  21.46     <30             1
4  1.72212  65.317301   29             24       Y  22.02     <30             1
5  1.74498  55.791862   50             26       N  18.32   46-60             0
6  1.77292  63.956524   51             22       Y  20.35   46-60             1
7  1.78054  61.688562   23             20       Y  19.46     <30             1
8  1.72466  50.802345   17             19       N  17.08     <30             0
9  1.69672  54.431084   39             31       N  18.91   30-45             0

In [24]:
age_hot_encode = pd.get_dummies(df["age_grp"], prefix="age")
df = pd.concat([df, age_hot_encode], axis=1)
df

,Height,Weight,Age,Grip Strength,Frailty,BMI,age_grp,Frailty_norm,age_30-45,age_46-60,age_<30
0,1.67132,50.802345,30,30,N,18.19,30-45,0,True,False,False
1,1.81610,61.688562,19,31,N,18.70,<30,0,False,False,True
2,1.76276,69.399633,45,29,N,22.33,30-45,0,True,False,False
3,1.73228,64.410117,22,28,Y,21.46,<30,1,False,False,True
4,1.72212,65.317301,29,24,Y,22.02,<30,1,False,False,True
5,1.74498,55.791862,50,26,N,18.32,46-60,0,False,True,False
6,1.77292,63.956524,51,22,Y,20.35,46-60,1,False,True,False
7,1.78054,61.688562,23,20,Y,19.46,<30,1,False,False,True
8,1.72466,50.802345,17,19,N,17.08,<30,0,False,False,True
9,1.69672,54.431084,39,31,N,18.91,30-45,0,True,False,False

In [25]:
df.to_csv("/content/DS-01/data/cleaned_data/fratility-cleaned.csv")

# **ANALYZE**

D. EDA & Reporting

In [26]:
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols]

    Height     Weight  Age  Grip Strength    BMI  Frailty_norm
0  1.67132  50.802345   30             30  18.19             0
1  1.81610  61.688562   19             31  18.70             0
2  1.76276  69.399633   45             29  22.33             0
3  1.73228  64.410117   22             28  21.46             1
4  1.72212  65.317301   29             24  22.02             1
5  1.74498  55.791862   50             26  18.32             0
6  1.77292  63.956524   51             22  20.35             1
7  1.78054  61.688562   23             20  19.46             1
8  1.72466  50.802345   17             19  17.08             0
9  1.69672  54.431084   39             31  18.91             0

In [27]:
summary = df[numeric_cols].agg(["mean","median","std"]).T
summary = summary.round(3)
print("\nSummary Statistics:")
print(summary)

Summary Statistics:
                 mean  median     std
Height          1.742   1.739   0.042
Weight         59.829  61.689   6.455
Age            32.500  29.500  12.860
Grip Strength  26.000  27.000   4.522
BMI            19.682  19.185   1.781
Frailty_norm    0.400   0.000   0.516

In [28]:
with open("/content/DS-01/reports/findings.md", "w") as f:
    f.write("# Frailty Study - Summary Report\n\n")
    f.write("## Summary Statistics\n\n")
    f.write(summary.to_markdown())

In [29]:
df.rename(columns={"Grip Strength": "Grip_Strength"}, inplace=True)
df

,Height,Weight,Age,Grip_Strength,Frailty,BMI,age_grp,Frailty_norm,age_30-45,age_46-60,age_<30
0,1.67132,50.802345,30,30,N,18.19,30-45,0,True,False,False
1,1.81610,61.688562,19,31,N,18.70,<30,0,False,False,True
2,1.76276,69.399633,45,29,N,22.33,30-45,0,True,False,False
3,1.73228,64.410117,22,28,Y,21.46,<30,1,False,False,True
4,1.72212,65.317301,29,24,Y,22.02,<30,1,False,False,True
5,1.74498,55.791862,50,26,N,18.32,46-60,0,False,True,False
6,1.77292,63.956524,51,22,Y,20.35,46-60,1,False,True,False
7,1.78054,61.688562,23,20,Y,19.46,<30,1,False,False,True
8,1.72466,50.802345,17,19,N,17.08,<30,0,False,False,True
9,1.69672,54.431084,39,31,N,18.91,30-45,0,True,False,False

In [30]:
correlation = df["Grip_Strength"].corr(df["Frailty_norm"])
print("\nCorrelation between Grip Strength and Frailty:")
print(round(correlation,4))

Correlation between Grip Strength and Frailty:
-0.4759